#server.tomcat.uri-encoding=UTF-8
server:
  port: 9090
  tomcat.uri-encoding: UTF-8
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  profiles:
    active: dev
  servlet.multipart.max-file-size: 10MB
  http.encoding:
    charset: UTF-8
    enabled: true
    force: true
  datasource:
    url: jdbc:mysql://localhost:3306/mobplus_db_local?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root123
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=3000
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hbm2ddl.auto: none
    show-sql: false

sms:
  appCode: cfe4652efa4b4857a9e5ca856fc1566c
  templateId: 20200710142300
  host: https://intlsms.market.alicloudapi.com
  path: /comms/sms/groupmessaging
  method: POST

qqPay:
  certPath: /data/server/ad-plus/gateway/cert/apiclient_cert.p12
  url: https://api.qpay.qq.com/cgi-bin/hongbao/qpay_hb_mch_send.cgi
  key: 1601064094

qq:
  openUrl: https://api.q.qq.com/sns/jscode2session

